services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app

    command:
      - "uv"
      - "run"
      - "fastapi"
      - "run"
      - "app/main.py"
      - "--host"
      - "0.0.0.0"

    ports:
      - "80:8000"
