services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "app/main.py",
        "--port",
        "80",
        "--host",
        "0.0.0.0",
      ]
    environment:
      - BUCKET_NAME
      - ENDPOINT
      - ACCESS_KEY
      - SECRET_KEY
    ports:
      - "80:80"
