services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "app/main.py",
        "--port",
        "80",
        "--host",
        "0.0.0.0",
      ]
    ports:
      - "8000:80"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:80"
  #   env_file:
  #     - ./frontend/.env
  #   volumes:
  #     - ./frontend:/code_frontend

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    env_file:
      - ./backend/.env
    command: server /data --console-address ":9001"
