version: "3.8"

services:
  backend:
    image: cr.yandex/${REGISTER_ID}/image-framer-backend:latest
    restart: always

  frontend:
    image: cr.yandex/${REGISTER_ID}/image-framer-frontend:latest
    restart: always

  nginx:
    image: nginx:1.25.3-alpine-slim
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
