services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "main.py",
        "--port",
        "80",
        "--host",
        "0.0.0.0",
      ]
    ports:
      - "80:80"
    env_file:
      - .env
