services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app

    command:
      - "uv"
      - "run"
      - "fastapi"
      - "run"
      - "app/main.py"
      - "--port"
      - "80"
      - "--host"
      - "0.0.0.0"

    ports:
      - "8000:80"
