services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "app/main.py",
        "--port",
        "80",
        "--host",
        "0.0.0.0",
      ]
    ports:
      - "80:80"
    env_file:
      - ./.env.prod

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    # volumes:
    #   - ./minio_data:/data
    env_file:
      - ./.env
    command: server /data --console-address ":9001"
