FROM python:3.13-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /code

COPY . /code

RUN uv sync --frozen --no-cache

EXPOSE 8000

ENTRYPOINT [ "uv", "run", "fastapi", "run", "app/main.py", "--host", "0.0.0.0"]

